### ISSUE TITLE
Makefile convention (mkdir -p before installing)

### ISSUE THREAD

**Issue by alex-tee** [tlsa/libcyaml#78] opened 2019-01-22 16:07 UTC
I'm trying to package your library (i know it's not released yet but i want to use it in my program) on fedora/arch linux/debian and I noticed something about your makefile.

It is common in other libraries when packaging for different distros that the makefile does mkdir -p before trying to install something somewhere. (in a fakeroot environment, you have to make the /usr/lib /usr/include etc. before installing) try doing `mkdir somedir && make DESTDIR=somedir install" to see what i mean

I can submit a pull request fixing it if you are okay with that.

PS. i'm a new packager and I might be wrong, but from my experience so far, other libraries and pretty much anything that uses autotools does that

thanks for your useful work!

**Comment by tlsa** [comment] 2019-01-22 17:34
Oh, good point.  I'll fix it this evening.  Thanks.

**Comment by alex-tee** [comment] 2019-01-22 18:00
BTW my fedora build was failing due to some SONAME issues.

I was told by #fedora-devel that the library must use the soname libcyaml.so.0

Here's what I did in case it's useful to you:
```
$(BUILDDIR)/$(LIB_SH_VER): $(LIB_OBJ_SHARED)
  $(CC) $(LDFLAGS) $(LDFLAGS_COV) -Wl,-soname=libcyaml.so.0 -shared -o $@ $^
```

**Comment by tlsa** [comment] 2019-01-22 19:38
The leading directories issue is fixed in pull request #79.

I'm not sure what the problem is with the SONAME.  The build system creates symlinks to the `libcyaml.so.0.0.0` which is .so file.

```
-rw-r--r-- 1 tlsa tlsa 177850 Jan 22 19:27 libcyaml.a
lrwxrwxrwx 1 tlsa tlsa     17 Jan 22 19:27 libcyaml.so -> libcyaml.so.0.0.0
lrwxrwxrwx 1 tlsa tlsa     17 Jan 22 19:27 libcyaml.so.0 -> libcyaml.so.0.0.0
-rwxr-xr-x 1 tlsa tlsa 105520 Jan 22 19:27 libcyaml.so.0.0.0
drwxr-xr-x 2 tlsa tlsa   4096 Jan 22 19:27 pkgconfig
```

**Comment by tlsa** [comment] 2019-01-22 19:54
> Here's what I did in case it's useful to you:
> 
> ```
> $(BUILDDIR)/$(LIB_SH_VER): $(LIB_OBJ_SHARED)
>   $(CC) $(LDFLAGS) $(LDFLAGS_COV) -Wl,-soname=libcyaml.so.0 -shared -o $@ $^
> ```

That breaks `make test` because it uses the library from the build directory, and that has the full .0.0.0 version.  The .0 symlink is only created at install time.

**Comment by alex-tee** [comment] 2019-01-22 19:59
try `objdump -p build/debug/libcyaml.so.0.0.0 | grep SONAME`

apparently when building RPM packages that needs to be the major version? I'm not sure either but the guys at #fedora-devel told me that it needs to be .0 in this case

**Comment by tlsa** [comment] 2019-01-22 20:46
Merged the install directories fix.

The other change currently breaks tests, so it needs more work: #80.

**Comment by tlsa** [comment] 2019-01-23 11:46
@alex-tee Please could you try with the latest master?  Also, were there any issues with debian and arch?  Or just fedora?

**Comment by alex-tee** [comment] 2019-01-23 12:48
@tlsa works great now! debian and arch worked from before. fedora is happy now too.

here's the repos btw:
https://copr.fedorainfracloud.org/coprs/alextee/zrythm/
https://aur.archlinux.org/packages/libcyaml-git/
https://gitlab.com/alextee/zrythm#debianlinux-mintubuntu (package is libcyaml)

**Closed** 2019-01-23 13:39 UTC
